from modules.util.enum.ModelType import ModelType
from modules.util.enum.TrainingMethod import TrainingMethod
from modules.webui.schema.types import Field, Group, Tab


def build_lora_embedding_tab(model_type: ModelType, training_method: TrainingMethod) -> Tab:
    return Tab(
        "lora_embedding",
        "LoRA",
        (
            Group(
                "lora",
                "LoRA",
                (
                    Field(
                        "peft-type",
                        ("peft_type",),
                        "PEFT Type",
                        "Parameter-efficient fine-tuning type",
                        "select",
                    ),
                    Field(
                        "lora-model-name",
                        ("lora_model_name",),
                        "Base Model",
                        "Base LoRA model file path or name",
                        "text",
                        path_mode="file",
                    ),
                    Field(
                        "lora-rank",
                        ("lora_rank",),
                        "LoRA Rank",
                        "Dimension rank for LoRA matrices",
                        "number",
                    ),
                    Field(
                        "lora-alpha",
                        ("lora_alpha",),
                        "LoRA Alpha",
                        "Scaling factor alpha for LoRA weights",
                        "number",
                    ),
                    Field(
                        "dropout-probability",
                        ("dropout_probability",),
                        "Dropout Probability",
                        "Dropout probability for LoRA / text encoder",
                        "number",
                    ),
                    Field(
                        "lora-weight-dtype",
                        ("lora_weight_dtype",),
                        "LoRA Weight Data Type",
                        "Data type for LoRA model weights",
                        "select",
                    ),
                    Field(
                        "bundle-additional-embeddings",
                        ("bundle_additional_embeddings",),
                        "Bundle Additional Embeddings",
                        "Bundle additional embeddings into LoRA output checkpoint",
                        "toggle",
                    ),
                    Field(
                        "lora-decompose",
                        ("lora_decompose",),
                        "Decompose Weights (DoRA)",
                        "Enable Weight-Decomposed Low-Rank Adaptation (DoRA)",
                        "toggle",
                    ),
                    Field(
                        "lora-decompose-norm-eps",
                        ("lora_decompose_norm_epsilon",),
                        "Use Norm Epsilon (DoRA Only)",
                        "Norm epsilon for DoRA weight magnitude normalization",
                        "toggle",
                    ),
                    Field(
                        "lora-decompose-output-axis",
                        ("lora_decompose_output_axis",),
                        "Apply on output axis (DoRA Only)",
                        "Use output axis for DoRA magnitude vector",
                        "toggle",
                    ),
                ),
            ),
            Group(
                "loha",
                "LoHa",
                (
                    Field(
                        "loha-model-name",
                        ("lora_model_name",),
                        "Base Model",
                        "Base LoHa model file path or name",
                        "text",
                        path_mode="file",
                    ),
                    Field(
                        "loha-rank",
                        ("lora_rank",),
                        "LoHa Rank",
                        "Dimension rank for LoHa matrices",
                        "number",
                    ),
                    Field(
                        "loha-alpha",
                        ("lora_alpha",),
                        "LoHa Alpha",
                        "Scaling factor alpha for LoHa weights",
                        "number",
                    ),
                    Field(
                        "loha-dropout-probability",
                        ("dropout_probability",),
                        "Dropout Probability",
                        "Dropout probability",
                        "number",
                    ),
                    Field(
                        "loha-weight-dtype",
                        ("lora_weight_dtype",),
                        "LoHa Weight Data Type",
                        "Data type for LoHa model weights",
                        "select",
                    ),
                    Field(
                        "loha-bundle-additional-embeddings",
                        ("bundle_additional_embeddings",),
                        "Bundle Additional Embeddings",
                        "Bundle additional embeddings into output checkpoint",
                        "toggle",
                    ),
                ),
            ),
            Group(
                "oft",
                "OFT v2",
                (
                    Field(
                        "oft-model-name",
                        ("lora_model_name",),
                        "Base Model",
                        "Base OFT v2 model file path or name",
                        "text",
                        path_mode="file",
                    ),
                    Field(
                        "oft-block-size",
                        ("oft_block_size",),
                        "OFT Block Size",
                        "Block size for Orthogonal Fine-Tuning",
                        "number",
                    ),
                    Field(
                        "oft-block-share",
                        ("oft_block_share",),
                        "Block Share",
                        "Share orthogonal block matrices across layers",
                        "toggle",
                    ),
                    Field(
                        "oft-scaled",
                        ("oft_scaled",),
                        "Scaled OFT (SOFT)",
                        "Use scaled orthogonal matrices in OFT",
                        "toggle",
                    ),
                    Field(
                        "oft-dropout-probability",
                        ("dropout_probability",),
                        "Dropout Probability",
                        "Dropout probability",
                        "number",
                    ),
                    Field(
                        "oft-weight-dtype",
                        ("lora_weight_dtype",),
                        "OFT Weight Data Type",
                        "Data type for OFT model weights",
                        "select",
                    ),
                    Field(
                        "oft-bundle-additional-embeddings",
                        ("bundle_additional_embeddings",),
                        "Bundle Additional Embeddings",
                        "Bundle additional embeddings into output checkpoint",
                        "toggle",
                    ),
                ),
            ),
            Group(
                "lokr",
                "LoKr",
                (
                    Field(
                        "lokr-model-name",
                        ("lora_model_name",),
                        "Base Model",
                        "Base LoKr model file path or name",
                        "text",
                        path_mode="file",
                    ),
                    Field(
                        "lokr-dim",
                        ("lokr_dim",),
                        "LoKr Dimension",
                        "Kronecker product dimension for LoKr",
                        "number",
                    ),
                    Field(
                        "lokr-decompose-factor",
                        ("lokr_decompose_factor",),
                        "Decomposition Factor",
                        "Factor for low-rank matrix decomposition",
                        "number",
                    ),
                    Field(
                        "lokr-alpha",
                        ("lora_alpha",),
                        "LoKr Alpha",
                        "Scaling factor alpha for LoKr weights",
                        "number",
                    ),
                    Field(
                        "lokr-dropout-probability",
                        ("dropout_probability",),
                        "Dropout Probability",
                        "Dropout probability",
                        "number",
                    ),
                    Field(
                        "lokr-weight-dtype",
                        ("lora_weight_dtype",),
                        "LoKr Weight Data Type",
                        "Data type for LoKr model weights",
                        "select",
                    ),
                    Field(
                        "lokr-vec-trick",
                        ("lokr_vec_trick",),
                        "Kronecker-Vec Trick",
                        "Use vectorization trick for faster Kronecker multiplication",
                        "toggle",
                    ),
                    Field(
                        "lokr-decompose-both",
                        ("lokr_decompose_both",),
                        "Decompose Both Matrices",
                        "Decompose both Kronecker matrix factors into low-rank",
                        "toggle",
                    ),
                    Field(
                        "lokr-use-tucker",
                        ("lokr_use_tucker",),
                        "Use Tucker Decomposition (Conv)",
                        "Use Tucker tensor decomposition for 4D convolutions",
                        "toggle",
                    ),
                    Field(
                        "lokr-full-matrix",
                        ("lokr_full_matrix",),
                        "Force Full Matrix (W2)",
                        "Use full matrix instead of Kronecker product decomposition",
                        "toggle",
                    ),
                    Field(
                        "lokr-weight-decompose",
                        ("lokr_weight_decompose",),
                        "Decompose Weights (DoRA)",
                        "Apply weight decomposition to LoKr updates",
                        "toggle",
                    ),
                    Field(
                        "lokr-dora-on-output",
                        ("lokr_dora_on_output",),
                        "Apply DoRA on Output Axis",
                        "Apply DoRA magnitude normalization on output axis",
                        "toggle",
                    ),
                    Field(
                        "lokr-bundle-additional-embeddings",
                        ("bundle_additional_embeddings",),
                        "Bundle Additional Embeddings",
                        "Bundle additional embeddings into output checkpoint",
                        "toggle",
                    ),
                ),
            ),
        ),
    )
